package com.ahmad.bigwaves;

import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.client.event.RenderLevelStageEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraft.client.Minecraft;
import com.mojang.blaze3d.vertex.PoseStack;

@Mod(BigWavesMod.MODID)
public class BigWavesMod {
    public static final String MODID = "bigwaves";

    public BigWavesMod() {
        MinecraftForge.EVENT_BUS.register(this);
    }

    @SubscribeEvent
    public void onRenderLevel(RenderLevelStageEvent event) {
        if (event.getStage() == RenderLevelStageEvent.Stage.AFTER_PARTICLES) {
            PoseStack poseStack = event.getPoseStack();
            float time = (Minecraft.getInstance().level.getGameTime() % 10000) / 20.0f;

            // Big wave motion
            float waveY = (float) Math.sin(time * 0.8f) * 0.3f;
            poseStack.translate(0, waveY, 0);
        }
    }
}
